on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited, unlocked]
    branches:
      - main

jobs:
  lint-client:
    defaults:
      run:
        working-directory: client

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run linter
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true


  lint-server:
    defaults:
      run:
        working-directory: server

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1

      - name: Run linter
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          golint: true

  lint-markdown:
    steps:
      - name: Run linter
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
